media:
  input: assets/images
  output: /assets/images

content:
  - name: posts
    label: "Blog-Artikel"
    type: collection
    path: '_posts'
    filename: '{year}-{month}-{day}-{fields.slug}.md'
    view:
      fields: [title, date, lang, category]
    fields:
      - { name: date, label: "Datum", type: date }
      - { name: title, label: "Titel", type: string }
      - { name: slug, label: "URL-Kürzel (ohne Leerzeichen, z.B. mein-erster-post)", type: string }
      - { name: page_id, label: "Page ID (gleich für DE+EN Versionen)", type: string }
      - name: lang
        label: "Sprache"
        type: select
        options:
          values:
            - { value: "de", label: "Deutsch" }
            - { value: "en", label: "English" }
      - name: category
        label: "Kategorie"
        type: select
        options:
          values: ["Training", "Ernährung", "Mentale Stärke", "Material", "Sonstiges"]
      - { name: author, label: "Autor", type: string }
      - { name: image, label: "Titelbild", type: image }
      - { name: excerpt, label: "Kurzbeschreibung (für Übersicht)", type: text }
      - { name: body, label: "Artikeltext", type: rich-text }
