title: K4 Endurance
description: Individuelles Trail- und Ultrarunning-Coaching mit K4 Endurance.
url: "https://www.k4endurance.com"

include:
  - _data

markdown: kramdown

# Blog-Einstellungen
plugins:
  - jekyll-paginate
permalink: /blog/:year/:month/:day/:title/
future: true

defaults:
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "de"
